"use client";
import {useEffect,useMemo,useState} from "react";

type News={title:string;summary:string;url:string;published:string;source:string;category:string;district:string};
const districts=["All Tamil Nadu","Ariyalur","Chengalpattu","Chennai","Coimbatore","Cuddalore","Dharmapuri","Dindigul","Erode","Kallakurichi","Kancheepuram","Kanyakumari","Karur","Krishnagiri","Madurai","Mayiladuthurai","Nagapattinam","Namakkal","The Nilgiris","Perambalur","Pudukkottai","Ramanathapuram","Ranipet","Salem","Sivaganga","Tenkasi","Thanjavur","Theni","Thoothukudi","Tiruchirappalli","Tirunelveli","Tirupattur","Tiruppur","Tiruvallur","Tiruvannamalai","Vellore","Viluppuram","Virudhunagar"];
const demo:News[]=[];

export default function Home(){
 const [items,setItems]=useState<News[]>(demo),[district,setDistrict]=useState("All Tamil Nadu"),[q,setQ]=useState(""),[dark,setDark]=useState(false),[saved,setSaved]=useState<string[]>([]),[loading,setLoading]=useState(true),[ai,setAi]=useState(""),[answer,setAnswer]=useState(""),[lastUpdated,setLastUpdated]=useState("");
 const loadNews=()=>{setLoading(true);fetch(`/api/news?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{setItems(d.items||[]);setLastUpdated(d.updatedAt||new Date().toISOString())}).catch(()=>{}).finally(()=>setLoading(false))};
 useEffect(()=>{loadNews();const timer=setInterval(loadNews,60000);return()=>clearInterval(timer)},[]);
 const filtered=useMemo(()=>items.filter(n=>(district==="All Tamil Nadu"||n.district===district)&&(`${n.title} ${n.summary} ${n.category} ${n.district}`).toLowerCase().includes(q.toLowerCase())),[items,district,q]);
 function speak(t:string){if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
 async function askAI(){setAnswer("Thinking...");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:ai,news:filtered.slice(0,8)})});const d=await r.json();setAnswer(d.answer||d.error||"AI is not configured yet.")}catch{setAnswer("AI service is not configured yet. Add GEMINI_API_KEY in Vercel environment variables.")}}
 return <div className={dark?"darkPage":""} style={dark?{background:"#0b1220",color:"#f8fafc",minHeight:"100vh"}:{}}>
  <div className="top"><div className="container topin"><span>🇮🇳 Tamil Nadu • AI-powered local news</span><span>{loading?"Updating live…":`🟢 Live • Updated ${lastUpdated?new Date(lastUpdated).toLocaleTimeString("en-IN"):"now"}`}</span></div></div>
  <header className="nav"><div className="container navin"><div className="logo">TAMILNADU <span>AI NEWS</span></div><nav className="links"><a href="#latest">Latest</a><a href="#trending">Trending</a><a href="#districts">Districts</a><a href="#ai">AI Assistant</a></nav><div className="actions"><button className="btn" onClick={loadNews}>↻ Refresh</button><button className="btn" onClick={()=>setDark(!dark)}>{dark?"☀️":"🌙"}</button></div></div></header>
  <main className="container">
   <section className="hero"><div className="heroGrid"><article className="heroCard"><span className="badge">🔴 LIVE NEWS</span><h1>Tamil Nadu news, explained by AI — in Tamil & English.</h1><p>Live publisher feeds refresh automatically every 60 seconds. Browse current stories by district, listen to headlines and ask AI about the latest feed.</p></article><aside className="side"><h3>⚡ Live Platform</h3><div className="breaking">📰 Fresh publisher headlines</div><div className="breaking">🔄 Automatic 60-second refresh</div><div className="breaking">🤖 Gemini-ready AI assistant</div><div className="breaking">📍 38-district filtering</div></aside></div></section>
   <section id="districts" className="section"><div className="sectionHead"><h2>📍 Explore all 38 districts</h2></div><div className="districts">{districts.map(d=><button key={d} className={"chip "+(district===d?"active":"")} onClick={()=>setDistrict(d)}>{d}</button>)}</div></section>
   <section id="trending" className="section"><div className="sectionHead"><h2>🔥 Latest / Trending</h2><input className="input" style={{maxWidth:280}} placeholder="Search Tamil Nadu news…" value={q} onChange={e=>setQ(e.target.value)}/></div>{filtered.length===0?<div className="notice">{loading?"Loading today's live news…":"No live stories match this district/search."}</div>:<div className="grid">{filtered.slice(0,6).map((n,i)=><NewsCard key={i} n={n} saved={saved.includes(n.url)} onSave={()=>setSaved(s=>s.includes(n.url)?s.filter(x=>x!==n.url):[...s,n.url])} speak={speak}/>)}</div>}</section>
   <section id="latest" className="section"><div className="sectionHead"><h2>📰 Latest News</h2><span className="meta">{filtered.length} live stories</span></div>{filtered.length>6&&<div className="grid">{filtered.slice(6,18).map((n,i)=><NewsCard key={i} n={n} saved={saved.includes(n.url)} onSave={()=>setSaved(s=>s.includes(n.url)?s.filter(x=>x!==n.url):[...s,n.url])} speak={speak}/>)}</div>}</section>
   <section id="ai" className="section"><div className="ai"><h2>🤖 Ask TamilNadu AI</h2><p>Ask questions about the current live news feed. Add <b>GEMINI_API_KEY</b> in Vercel to enable live AI answers.</p><div className="aiRow"><input className="input" value={ai} onChange={e=>setAi(e.target.value)} placeholder="உதாரணம்: கோவையில் முக்கிய செய்திகள் என்ன?"/><button className="btn" onClick={askAI}>Ask AI</button></div>{answer&&<p className="summary" style={{marginTop:15}}><b>AI:</b> {answer}</p>}</div></section>
  </main><footer className="footer"><div className="container"><strong>TamilNadu AI News</strong><p>Live headlines and short summaries are sourced from publisher RSS feeds and link back to the original story. The feed refreshes automatically throughout the day.</p></div></footer>
 </div>
}
function NewsCard({n,saved,onSave,speak}:{n:News;saved:boolean;onSave:()=>void;speak:(x:string)=>void}){return <article className="card"><div className="thumb">📰</div><div className="cardbody"><span className="tag">{n.category} • {n.district}</span><h3>{n.title}</h3><p className="summary">{n.summary}</p><span className="meta">{n.source} • {n.published?new Date(n.published).toLocaleString("en-IN"):""}</span><div style={{display:"flex",gap:7,marginTop:12}}><button className="btn" onClick={()=>speak(n.title+". "+n.summary)}>🔊</button><button className="btn" onClick={onSave}>{saved?"★ Saved":"☆ Save"}</button>{n.url!=="#"&&<a className="btn" href={n.url} target="_blank" rel="noreferrer">Read ↗</a>}</div></div></article>}
